"""empty message

Revision ID: 560aa90fe258
Revises: 65be84bcac0f
Create Date: 2017-11-01 16:19:13.577948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560aa90fe258'
down_revision = '65be84bcac0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
