"""empty message

Revision ID: 7a67e81a0c7d
Revises: 185b2262123f
Create Date: 2017-11-01 20:06:22.457165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a67e81a0c7d'
down_revision = '185b2262123f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'confirmed')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
