"""empty message

Revision ID: fc0290147fb7
Revises: 560aa90fe258
Create Date: 2017-11-01 17:43:13.160293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0290147fb7'
down_revision = '560aa90fe258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
